easy_admin:
  entities:
    AffaireUtilisateur:
      class: AppBundle\Entity\AffaireUtilisateur
      controller: AppBundle\Controller\Admin\Model\AffaireUtilisateurController
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'