lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase:      'Admin@123' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600

