twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        FileSizeJob: '@App\Service\FileSizeJob'
        FileToImg: '@App\Service\FileToImg'
