#index:
#    path: /
#    controller: App\Controller\DefaultController::index
swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui

authentication_token:
  path: /authentication_token
  methods: ['POST']